if [[ "$(uname)" == "Darwin" ]]; then
  # macOS (Apple Silicon)
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ "$(uname)" == "Linux" ]]; then
  # Linux
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

eval "$(rbenv init - --no-rehash zsh)"
