echo "BE ALL THAT YOU CAN BE!"

export PS1="kaitokimura %1~ %# "

# Zsh 補完システムの初期化
autoload -Uz compinit
compinit

export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000

setopt no_beep
setopt auto_pushd
setopt pushd_ignore_dups
setopt hist_ignore_dups
setopt share_history
setopt inc_append_history

# kubectl
source <(kubectl completion zsh)

# Haskell GHCup
[ -f "$GHCUP_ENV" ] && source "$GHCUP_ENV"

# Ocaml
[[ ! -r "$OPAM_INIT" ]] || source "$OPAM_INIT"  > /dev/null 2> /dev/null

alias vi="nvim"
alias vim="nvim"
alias view="nvim -R"

