echo "BE ALL THAT YOU CAN BE!"

export PS1="kaitokimura %1~ %# "

# Zsh 補完システムの初期化
autoload -Uz compinit
compinit

# kubectl
source <(kubectl completion zsh)

# Haskell GHCup
[ -f "$GHCUP_ENV" ] && source "$GHCUP_ENV"

# Ocaml
[[ ! -r "$OPAM_INIT" ]] || source "$OPAM_INIT"  > /dev/null 2> /dev/null


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
